version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: pg-main
    environment:
      POSTGRES_PASSWORD: AhmadSajidSura2003
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init-multi-db.sql:/docker-entrypoint-initdb.d/init-multi-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
