server:
  port: 8444
  ssl:
    enabled: true
    key-store: classpath:certs/keystore.jks
    key-store-password: user123
    key-store-type: JKS
    trust-store: classpath:certs/keystore.jks
    trust-store-password: user123
    trust-store-type: JKS

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: AhmadSajidSura2003
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

security:
  jwt:
    access-seconds: 900
    refresh-seconds: 604800
