server:
  port: 8445
  ssl:
    enabled: true
    key-store: classpath:tls/userEntity-keystore.p12
    key-store-password: user123
    key-store-type: PKCS12

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: AhmadSajidSura2003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

security:
  jwt:
    public-key: classpath:certs/jwt-public.pem
    issuer: user-service
    expiration: 3600
    access-seconds: 900
    refresh-seconds: 604800
    hmac-secret: "0123456789ABCDEF0123456789ABCDEF"
  filter-chain:
    permit-all-patterns:
      - "/v3/api-docs/**"
      - "/swagger-ui/**"
      - "/swagger-ui.html"
      - "/api/admin/login"
    admin-patterns:
      - "/api/admin/**"
    authorities-claim-name: "roleEntities"
    authority-prefix: ""

admin-service:
  url: https://localhost:8446
  trust-store: classpath:tls/admin-truststore.p12
  trust-store-password: user123

logging:
  level:
    com.example.admin: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: TRACE
    org.springframework.security: INFO
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG
