server:
  port: 8445
  ssl:
    enabled: true
    key-store: classpath:tls/user-keystore.p12
    key-store-password: user123
    key-store-type: PKCS12
    trust-store: classpath:tls/user-truststore.p12
    trust-store-password: user123
    trust-store-type: PKCS12

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: AhmadSajidSura2003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

security:
  jwt:
    public-key: classpath:certs/jwt-public.pem
    issuer: user-service
    expiration: 3600
    access-seconds: 900
    refresh-seconds: 604800
admin-service:
  url: https://localhost:8446
  trust-store: classpath:tls/admin-truststore.p12
  trust-store-password: user123
