server:
  port: 8082
  ssl:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/admin_db
    username: postgres
    password: AhmadSajidSura2003

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    enabled: true

user-service:
  url: http://localhost:8081

s2s:
  audience: user-service

jwt:
  private-key-location: classpath:certs/jwt-private-pkcs8.pem
  public-key-location: classpath:certs/jwt-public.pem
  key-id: microservice-shared-key-id

logging:
  level:
    com.example.admin: DEBUG
